### PR TITLE
Add support for elevation

### PR DESCRIPTION
**Pull request by anderscheow**
This PR allows user to set elevation to the alert background.

### CODE REVIEW

**Comment by kpmmmurphy** [comment]
That's awesome @anderscheow, thanks for this! We're good to merge, once you update the library version, and changelog! 🙌

**Comment by anderscheow** [comment]
Done updating the version and changelog!

**Comment by anderscheow** [comment]
Somehow release 7.2.3 doesn't include this changes. Can you check on it?

**Comment by kpmmmurphy** [comment]
Apologies @anderscheow, I've updated the tags now to reflect the correct commits. Please try again now

**Comment by anderscheow** [comment]
I just checked, still the same.

**Comment by anderscheow** [comment]
I suggest to bump another version, because Jitpack already cached for 7.2.3

**Comment by kpmmmurphy** [comment]
Apologies. I've updated the release again... Please clear you local Gradle cache and try again!

**Comment by anderscheow** [comment]
Thanks mate!

**Comment by anderscheow** [comment]
Hi sorry to disturb again. Seems like the Jitpack not updated the 7.2.3 with the latest changes that you've done.

**Comment by kpmmmurphy** [comment]
Sorry @anderscheow, I've gone ahead and bumped to 7.2.4! Tested locally myself, and your code is included this time!

**Comment by anderscheow** [comment]
Much appreciated!

**Pull request merged**
