### PR TITLE
Alerter can be appear from bottom or center

### PR DESCRIPTION
**Pull request by rezaiyan**
#163 #181

### CODE REVIEW

**Comment by kpmmmurphy** [comment]
Hey @rezaiyan, thanks for your PR! Looks good, one last step is to update the version in the build.gradle, and the changelog! Then we're good to merge 🚀

**Comment by dosomder** [comment]
@rezaiyan I have an issue when showing the alerter at the bottom. Looks like alert is moved to the left
grafik

**Comment by rezaiyan** [comment]
> @rezaiyan I have an issue when showing the alerter at the bottom. Looks like alert is moved to the left.
> Any idea what the problem is? I suppose it has something to do with the padding you set when not using Gravity.TOP
> 
> grafik

Yeah, It seems has no padding on left side
I'll fix it.

**Comment by dosomder** [comment]
Thanks @rezaiyan 
Also I think the notch height can be disregarded when not using TOP, right?

**Comment by rezaiyan** [comment]
> Thanks @rezaiyan
> Also I think the notch height can be disregarded when not using TOP, right?

Yes, but if the notch height being removed, the extra padding of the bottom must be removed too, then it makes the Alerter thin.

**Pull request merged**
