### PR TITLE
Add new Functionality

### PR DESCRIPTION
**Pull request by dalwadi2**
Add the functionality to set Outside touch enable/disable, By default it is Disable. Written comments for Javadoc and added the example of new functionality called, setOutsideClickable

### CODE REVIEW

**Comment by sboyokis** [comment]
Hello, 

I confirm, we need it. Please can you take a look on this commit and merge if its ok ?

**Comment by dalwadi2** [comment]
@sboyokis are you talking to me?

**Comment by sboyokis** [comment]
No sry,  to @kpmmmurphy.

@dalwadi2  But nice work, you add an interesting functionality

**Comment by dalwadi2** [comment]
thanks @sboyokis

**Comment by kpmmmurphy** [comment]
Hi @dalwadi2 - I'm not sure how valuable this feature, and the implementation is invasive in my opinion. I use Drawable State lists with different resources for enabled and disabled states - With your implementation, it would cause these to change, which might not be the desired behaviour.

**Comment by dalwadi2** [comment]
It'll not affect your existing functionality, @kpmmmurphy  I've tested.
If you find the bug in this new functionality then let me know.
thanks.

**Comment by sboyokis** [comment]
for me it's not closed, you should consider to add this functionality

**Comment by dalwadi2** [comment]
what is your problem @kpmmmurphy ? I clearly said that show me the bug if any of my code affecting your existing library then I'll never contribute here. but you just close the pull request without any reason that's not an action that you've taken.

**Comment by kpmmmurphy** [comment]
Hi @dalwadi2, sorry if I've upset you. Your `outsideTouchable ` loops through the child views of the current Activity's root view. This is invasive and will cause knock-on bugs for apps which use this library - and that's bad. 

Alternatively, you could refactor the Alert view's XML to be a full screen layout, with an invisible view which acts as an overlay to stop touches occurring - then programatically enable and disable this. Does that make sense? 

Also, ensure you stick to the code standards & conventions - No Hungarian case notation please.

**Comment by sboyokis** [comment]
Hi @dalwadi2 @kpmmmurphy calm down guys :). 

We are here for share. @kpmmmurphy has the rights to not merge the pull request. 

@dalwadi2 has right about the outside touch functionality : we need it. 

I like the suggestion to refactor the Alert view's XML. We should work on it and do a new pull request. 

@kpmmmurphy may be at the same time, we should add the size option (width & height) about the alert snackbar? Or may be your are already working on it ?

**Pull request closed without merging**
